name: Destroy Stack
on:
 workflow_dispatch:
  inputs:
    environment_name:
      description: 'The name of the environment to destroy resources from dev or test or prod(BE CAREFUL HERE)'
      required: true
      default: 'dev'
      type: choice
      options:
        - dev
        - test
        - prod
    app_env:
      required: true
      type: choice
      description: 'The APP env separates between AWS ENV and Actual APP, since AWS dev is where PR, and TEST is deployed'
      options:
        - dev
        - test
        - prod
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
jobs:
  destroy-dev:
    name: Destroy Stack Dev
    if: ( github.event.inputs.app_env == 'dev' )
    uses: ./.github/workflows/.destroy_stack.yml
    secrets: inherit
    with:
      environment_name: ${{ github.event.inputs.environment_name }}
      app_env: ${{ github.event.inputs.app_env }}
  destroy-test:
    name: Destroy Stack Test
    if: ( github.event.inputs.app_env == 'test' )
    uses: ./.github/workflows/.destroy_stack.yml
    secrets: inherit
    with:
      environment_name: ${{ github.event.inputs.environment_name }}
      app_env: ${{ github.event.inputs.app_env }}
  destroy-prod:
    name: Destroy Stack PROD
    if: ( github.event.inputs.app_env == 'prod' )
    uses: ./.github/workflows/.destroy_stack.yml
    secrets: inherit
    with:
      environment_name: ${{ github.event.inputs.environment_name }}
      app_env: ${{ github.event.inputs.app_env }}